# site settings
title: Forty
subtitle: by HTML5 UP
email: oluwatobi.adetula1@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

domain: blog.tobiadetula.com      # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://blog.tobiadetula.com   # the base hostname and protocol for your site, e.g. http://example.com
# baseurl: /REPOSITORY-NAME/      # place folder name if the site is served in a subfolder

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/tobiadetula
  GitLab:
  # Google-Plus: https://plus.google.com/u/0/tobiadetula
  Instagram:
  LinkedIn: https://www.linkedin.com/in/tobiadetula
  Twitter: https://twitter.com/tobiadetula
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
